# Generated by Django 4.2.13 on 2024-06-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_folder_creator_alter_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='01:07:02'),
        ),
    ]
