# Generated by Django 4.2.13 on 2024-06-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='access_users',
            field=models.ManyToManyField(blank=True, null=True, to='apps.care_giver'),
        ),
        migrations.AlterField(
            model_name='care_giver',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, to='apps.care_recipient'),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='07:13:02'),
        ),
    ]
