# Generated by Django 4.2.13 on 2024-06-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_board_access_users_alter_care_giver_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='07:41:18'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
