# Generated by Django 4.2.13 on 2024-06-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_history_time_alter_tab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(default='#cc4b48', max_length=50),
        ),
        migrations.AddField(
            model_name='tab',
            name='color',
            field=models.CharField(default='#619451', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='07:45:02'),
        ),
    ]
