# Generated by Django 4.2.13 on 2024-10-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_history_board_alter_codes_time_alter_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='time',
            field=models.TimeField(default='06:16:42'),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default='06:16:42'),
        ),
    ]
